accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [

    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),

]

blog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from . import views
from posts.api.serializers import GroupList , UserDetails, UserList
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from posts import views as posts_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^about/', views.about),
    url(r'^$', posts_views.post_list, name='home'),
    url(r'^api/', include('posts.api.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('users/', UserList.as_view()),
    path('users/<pk>/', UserDetails.as_view()),
    path('groups/', GroupList.as_view()),
]

urlpatterns +=  staticfiles_urlpatterns()

posts/api/urls.py
from django.urls import path, include
from django.conf.urls import url

from django.contrib import admin
from posts.api.serializers import GroupList , UserDetails, UserList
from .views import PostView
from rest_framework import routers

router = routers.DefaultRouter()
router.register('posts', PostView)

urlpatterns = [
    url(r'^', include(router.urls)),
]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.post_list, name="list"),
    url(r'^create$', views.create_post, name="create"),
    url(r'^(?P<slug>[\w-]+)/', views.article_detail, name="detail"),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    # add author later

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "[...]"


class Comment(models.Model):
    body = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.body[:40]

posts/forms.py
from django import forms
from . import models

class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'slug', 'body']

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['body']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def signup_view(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # login
            login(request, user)
            return redirect('posts:list')

    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('posts:list')

    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):

    if request.method == 'POST':
        logout(request)
        return redirect('posts:list')

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

posts/api/views.py
from rest_framework import viewsets, permissions
from posts.models import Post
from .serializers import PostSerializer
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden



class PostView(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    #permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def list(self, req):
        return super().list(req)

    def create(self, request):
        request.data["author"] = User.objects.get(username = request.user).pk
        return super().create(request)

    def update(self, request, pk=None):
        aut = Post.objects.get(pk=pk).author
        if aut == request.user:
            request.data["author"] = User.objects.get(username=request.user).pk
            return super().update(request, pk)
        else:
            return HttpResponseForbidden()

    def partial_update(self, request, pk=None):
        aut = Post.objects.get(pk=pk).author
        if aut == request.user:
            request.data["author"] = User.objects.get(username=request.user).pk
            return super().partial_update(request, pk)
        else:
            return HttpResponseForbidden()

    def destroy(self, request, pk=None):
        aut = Post.objects.get(pk=pk).author
        if aut == request.user:
            request.data["author"] = User.objects.get(username=request.user).pk
            return super().destroy(request, pk)
        else:
            return HttpResponseForbidden()

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from . import forms
from oauth2_provider.decorators import protected_resource

def post_list(request):

    posts = Post.objects.all().order_by('date')

    return render(request, 'posts/post_list.html', {'posts': posts})


def article_detail(request, slug):

    post = Post.objects.get(slug=slug)
    comment = Comment.objects.filter(post=post).order_by('-id')

    if request.method == 'POST':
        comment_form = forms.CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('body')
            comment = Comment.objects.create(post=post, author=request.user, body=content)
            comment.save()
            return redirect('posts:list')
    else:
        comment_form = forms.CommentForm()

    return render(request, 'posts/post_detail.html', {'post': post, 'comment': comment, 'comment_form': comment_form})


@login_required(login_url="/accounts/login/")
#@protected_resource()
def create_post(request):

    if request.method == 'POST':
        form = forms.PostForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('posts:list')
    else:
        form = forms.PostForm()
    return render(request, 'posts/create_post.html', {'form': form})

#def delete_post(request, slug):
    #post = Post.objects.get(slug=slug)


        #form = forms.PostForm(request.POST, instance=post)
    #post.delete()
    #return redirect('posts:list')
    #posts = Post.objects.all().order_by('date')
    #return render(request, 'posts/post_list.html', {'posts': posts})




# def create_comment(request):

    #if request.method == 'POST':
    #    form = forms.CommentForm(request.POST)
    #    if form.is_valid():
    #        instance = form.save(commit=False)
    #        post = Post.objects.get(slug=slug)
    #        instance.post = post.pk
    #        instance.save()
    #        return redirect('posts:detail')
    #else:
    #form = forms.CommentForm()
    #return render(request, 'posts/create_comment.html', {'form': form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

<form class="site-form" action="{% url 'accounts:login' %}" method="post">

    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}

    <input type="submit" value="Login">
    <br>
    <br>
    <h3>Not signed up yet? Create an account <a href="{% url 'accounts:signup' %}">here.</a></h3>
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

<form class="site-form" action="/accounts/signup/" method="post">

    {% csrf_token %}
    {{form}}

<input type="submit" value="Signup">
</form>
{% endblock %}

posts/templates/posts/create_comment.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="create-comment">
    <h2>
        Create a Comment!
    </h2>
    <form class="site-form" action="{% url 'posts:comment' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Create Comment">
    </form>

</div>

{% endblock %}

posts/templates/posts/create_post.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="create-post">
    <h2>
        Create a Post!
    </h2>
    <form class="site-form" action="{% url 'posts:create' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Create">
    </form>

</div>
<script src="/static/slugify.js"></script>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="post-detail">
    <div class="post">
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
        <p>Author: {{ post.author}}</p>
        <p>{{ post.date }}</p>




        <br><br>
        <hr>




        <form method="post">
            {% csrf_token %}
            {{ comment_form }}

            {% if user.is_authenticated %}
            <input type="submit" value="Submit">
            {% else %}
            <input type="submit" value="Submit" disabled>
            {% endif %}
        </form>


        <br>
        <h2>{{ comment.count }} Comment{{ comment|pluralize }}</h2>
        <div class="main-comment-section">

            {% for comment in comment %}
            <br>
            <h3>{{comment.body}}</h3>
            <p>by {{ comment.author}}</p>
            {% endfor %}

        </div>


    </div>
</div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base_layout.html' %}

{% block content %}

    <h1>Posts</h1>
    <br>
    <div class="posts">

        {% if user.is_authenticated %}
        <form class="create-link" action="{% url 'posts:create' %}" method="get">
            {% csrf_token %}
            <button type="submit">Create a Post</button>
        </form>
        {% endif %}

    <br>
        {% for post in posts %}
            <div class="post">
                <h2><a href="{% url 'posts:detail' slug=post.slug %}">{{post.title}}</a></h2>
                <p>{{post.snippet}}</p>
                <p>Author: {{post.author}}</p>
                <p>{{post.date}}</p>
                <br>
            </div>
        {% endfor %}

    </div>

{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
<h1>About us!</h1>
<p>We like Django!</p>
</body>
</html>

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Posts</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>

    <div class="wrapper">

        <h1><a href="{% url 'posts:list' %}"><img src="{% static 'blog.jpeg' %}"></a></h1>


        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
                </li>
                {% else %}
                <li>
                    <form class="login-link" action="{% url 'accounts:login' %}" method="get">
                        {% csrf_token %}
                        <button type="submit">Login</button>
                    </form>
                </li>
                {% endif %}
            </ul>
        </nav>


        {% block content %}
        {% endblock %}

    </div>

</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the homepage!</h1>
    <p>This is my page!</p>
</body>
</html>